/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.powerball;

import com.rubyplay.shyshov.powerball.PowerballEngine;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        PowerballEngine classUnderTest = new PowerballEngine();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.draw().size() == 6);
    }
}
