/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rubyplay.shyshov.powerball;

import com.rubyplay.shyshov.powerball.PowerballEngine;
import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class PowerballEngineTest {
    @Test public void testDraw() {
        PowerballEngine engine = new PowerballEngine();
        engine.startGame();
        ArrayList<Integer> result = engine.draw();
        assertTrue("draw should return 6 numbers", result.size() == 6);
        for (int i = 0; i < 5; i++) {
            assertTrue("draw ball numbers should be from 1 to 69", (result.get(i) > 0 && result.get(i) < 70));
        }
        assertTrue("power ball should be 1 to 26", (result.get(5) > 0 && result.get(5) < 27));
    }
}
